name: agricola
description: "Agricola, Master of Britain"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  path: ^1.9.0
  path_provider: ^2.1.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  flutter_markdown: ^0.7.3+1
  sqflite_common_ffi: ^2.3.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  assets:
   - assets/images/thumbnail.png
   - assets/images/map.png
   - assets/images/display.png
   - assets/images/battle_auxiliary_blue_1_3.png
   - assets/images/battle_auxiliary_blue_2_3.png
   - assets/images/battle_auxiliary_green_2_3.png
   - assets/images/battle_auxiliary_green_2_4.png
   - assets/images/battle_auxiliary_green_3_4.png
   - assets/images/battle_auxiliary_tan_2_4.png
   - assets/images/battle_auxiliary_tan_3_4.png
   - assets/images/battle_legionary_2_4_1.png
   - assets/images/battle_legionary_3_5_2.png
   - assets/images/battle_legionary_3_6_3.png
   - assets/images/battle_tribe_4_4.png
   - assets/images/battle_tribe_4_5.png
   - assets/images/battle_tribe_5_5.png
   - assets/images/battle_tribe_5_6.png
   - assets/images/battle_tribe_6_6.png
   - assets/images/battle_tribe_graupius_4_4.png
   - assets/images/battle_tribe_graupius_4_5.png
   - assets/images/battle_tribe_graupius_5_5.png
   - assets/images/battle_tribe_graupius_5_6.png
   - assets/images/battle_tribe_graupius_6_6.png
   - assets/images/map_garrison.png
   - assets/images/map_leader_agricola.png
   - assets/images/map_leader_green.png
   - assets/images/map_leader_red_calgacus.png
   - assets/images/map_leader_tan.png
   - assets/images/map_legion_augusta_II.png
   - assets/images/map_legion_hispana_IX.png
   - assets/images/map_legion_valeria_victrix_xx.png
   - assets/images/map_settlement_2.png
   - assets/images/map_settlement_3.png
   - assets/images/map_tribe_brigantes_5.png
   - assets/images/map_tribe_brigantes_6.png
   - assets/images/map_tribe_caledonii_7.png
   - assets/images/map_tribe_catuvellani_2.png
   - assets/images/map_tribe_corieltavvi_2.png
   - assets/images/map_tribe_cornovvi_4.png
   - assets/images/map_tribe_cornovvi_5.png
   - assets/images/map_tribe_damnonii_5.png
   - assets/images/map_tribe_deceangli_5.png
   - assets/images/map_tribe_deceangli_6.png
   - assets/images/map_tribe_demetae_3.png
   - assets/images/map_tribe_demetae_4.png
   - assets/images/map_tribe_dubbini_2.png
   - assets/images/map_tribe_iceni_3.png
   - assets/images/map_tribe_ordovices_4.png
   - assets/images/map_tribe_ordovices_5.png
   - assets/images/map_tribe_ordovices_6.png
   - assets/images/map_tribe_parisi_4.png
   - assets/images/map_tribe_parisi_5.png
   - assets/images/map_tribe_silures_4.png
   - assets/images/map_tribe_silures_5.png
   - assets/images/map_tribe_taexali_6.png
   - assets/images/map_tribe_venicones_6.png
   - assets/images/map_tribe_votadini_4.png
   - assets/images/map_tribe_votadini_5.png
   - assets/images/map_tribe_votadini_6.png
   - assets/images/marker_1.png
   - assets/images/marker_10.png
   - assets/images/marker_game_turn.png
   - assets/images/marker_income.png
   - assets/images/marker_legion_actions.png
   - assets/images/marker_treasury.png
   - assets/images/d8_1.png
   - assets/images/d8_2.png
   - assets/images/d8_3.png
   - assets/images/d8_4.png
   - assets/images/d8_5.png
   - assets/images/d8_6.png
   - assets/images/d8_7.png
   - assets/images/d8_8.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
