name: nubia
description: "Nubia: Egyptâ€™s Black Heirs"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  path: ^1.9.0
  path_provider: ^2.1.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  flutter_markdown: ^0.7.3+1
  sqflite_common_ffi: ^2.3.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  assets:
   - assets/images/map.png
   - assets/images/tray.png
   - assets/images/thumbnail.png
   - assets/images/asset_army.png
   - assets/images/asset_kingship.png
   - assets/images/asset_nobility.png
   - assets/images/bishop_5.png
   - assets/images/bishop_f.png
   - assets/images/bishop_i.png
   - assets/images/crusades_0.png
   - assets/images/crusades_1.png
   - assets/images/crusades_2.png
   - assets/images/dynastic_marriage.png
   - assets/images/eparch.png
   - assets/images/ethiopians.png
   - assets/images/famine.png
   - assets/images/feudal_n1.png
   - assets/images/feudal_p1.png
   - assets/images/land_sale_2.png
   - assets/images/land_sale_3.png
   - assets/images/land_sale_4.png
   - assets/images/mek_ayyubid.png
   - assets/images/mek_beja.png
   - assets/images/mek_funj.png
   - assets/images/mek_jad.png
   - assets/images/mek_juhayna.png
   - assets/images/mek_kanz.png
   - assets/images/mek_kawahla.png
   - assets/images/mek_mamluk.png
   - assets/images/mek_shilluk.png
   - assets/images/metropolitan_jesus.png
   - assets/images/metropolitan_john.png
   - assets/images/metropolitan_peter.png
   - assets/images/metropolitan_shenoute.png
   - assets/images/migration_a.png
   - assets/images/migration_b.png
   - assets/images/migration_c.png
   - assets/images/migration_d.png
   - assets/images/migration_e.png
   - assets/images/monastery_4.png
   - assets/images/monastery_5.png
   - assets/images/monastery_6.png
   - assets/images/mosque.png
   - assets/images/nubian_archers.png
   - assets/images/portugal.png
   - assets/images/princess_agatha.png
   - assets/images/princess_anthelia.png
   - assets/images/princess_kristina.png
   - assets/images/princess_mariam.png
   - assets/images/princess_martha.png
   - assets/images/princess_petronia.png
   - assets/images/slaves.png
   - assets/images/uru_abraham.png
   - assets/images/uru_cyriac.png
   - assets/images/uru_david.png
   - assets/images/uru_george.png
   - assets/images/uru_joel.png
   - assets/images/uru_kerenbes.png
   - assets/images/uru_mark.png
   - assets/images/uru_mercury.png
   - assets/images/uru_moses_george.png
   - assets/images/uru_rafael.png
   - assets/images/uru_solomon.png
   - assets/images/uru_zachary.png
   - assets/images/card_1.png
   - assets/images/card_2.png
   - assets/images/card_3.png
   - assets/images/card_4.png
   - assets/images/card_5.png
   - assets/images/card_6.png
   - assets/images/card_7.png
   - assets/images/card_8.png
   - assets/images/card_9.png
   - assets/images/card_10.png
   - assets/images/card_11.png
   - assets/images/card_12.png
   - assets/images/card_13.png
   - assets/images/card_14.png
   - assets/images/card_15.png
   - assets/images/card_16.png
   - assets/images/card_17.png
   - assets/images/card_18.png
   - assets/images/card_19.png
   - assets/images/card_20.png
   - assets/images/card_21.png
   - assets/images/card_22.png
   - assets/images/card_23.png
   - assets/images/card_24.png
   - assets/images/card_25.png
   - assets/images/card_26.png
   - assets/images/card_27.png
   - assets/images/card_back.png
   - assets/images/d6_1.png
   - assets/images/d6_2.png
   - assets/images/d6_3.png
   - assets/images/d6_4.png
   - assets/images/d6_5.png
   - assets/images/d6_6.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
